http:
  routers:

    astro-router:
      rule: "Host(`local.pulpo.cloud`)"
      service: "astro-service"
      entryPoints:
        - "websecure"
      tls: {}

  services:
    astro-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:4321"

tls:
  certificates:
    - certFile: /certs/cert.pem
      keyFile: /certs/key.pem