services:
  directus:
    build: . # Nutzt unser Dockerfile von oben
    ports:
      - 8055:8055
    environment:
      KEY: "dein-super-geheimer-key"
      SECRET: "dein-super-geheimes-secret"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "password"
      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"
      # WICHTIG: Damit Extensions geladen werden
      EXTENSIONS_PATH: "/directus/extensions"
    depends_on:
      - database
      - redis

  database:
    image: postgis/postgis:13-master
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6

volumes:
  postgres_data:
