volumes:
  postgres_data:
  directus_uploads:

services:
  directus:
    build:
      context: ../..
      dockerfile: apps/directus/Dockerfile
    container_name: directus
    ports:
      - 8055:8055
    environment:
      CORS_ENABLED: true
      CORS_ORIGIN: true
      CORS_METHODS: GET,POST,PATCH,DELETE
      CORS_HEADERS: Content-Type,Authorization
      CORS_CREDENTIALS: true
      
      PUBLIC_URL: http://localhost:8055
      KEY: "dein-super-geheimer-key"
      SECRET: "dein-super-geheimes-secret"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "password"
      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"
      # WICHTIG: Damit Extensions geladen werden
      EXTENSIONS_PATH: "/directus/extensions"
    volumes:
      - directus_uploads:/directus/uploads
    depends_on:
      - database
      - redis

  database:
    image: postgis/postgis:13-master
    container_name: directus_db
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: directus_redis

  mail:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025

